language: python

python:
  - "3.6"

jobs:
  include:
    # Check the plugin with kodi-addon-checker
    - stage: kodi-addon-checker
      script:
        - pip install kodi-addon-checker
        - kodi-addon-checker --branch krypton --allow-folder-id-mismatch ./resource.images.catchuptvandmore

    # Update repository.catchuptvandmore
    - stage: update-repo
      script: 
        - pip install gitpython
        - git clone https://github.com/Catch-up-TV-and-More/repository.catchuptvandmore ../repo
        - cd ../repo
        - git config --global user.email "travis@travis-ci.org"
        - git config --global user.name "Travis CI"
        - git remote set-url origin https://${GH_TOKEN}@github.com/Catch-up-TV-and-More/repository.catchuptvandmore.git > /dev/null 2>&1
        - ./update_all_repos.sh

notifications:
  email:
    on_success: always
    on_failure: always

env:
  global:
    secure: e7GXzlD/y/LTxATIFuGYr8zX5g17D6TzESs3GWqRMhbbthJejwrQiO2dTVQBKBUTVWdHxGBWN/90Y8crebySIbmy16DlJ2f/xnDGkCwIjvOhy2I1uOS5X0SIGpHNJnvlyRscmPr81X+3sRQshFDbfnm3Jf72/mnQImEO/JhjVGM2iG3UZTFf5YB1Hai0QXDcbifUNqYBIwDdpTbyKMf32f5qjwMeh21IRuaB316GwkBuZdB7hH3dpQM1Q7tqWJkONUFG5kwup23bf0zIdrFIhpNHASAs5Yz2ccMgZrusPZPuW/Y/xX2KBz5KjlS4MxExQLJW7oKoaaSNcgSiZwkxdksYnIvOmlFWmnzljM3gO1/Rx2P5lp0kw0NbaRzylTW6p2TdoDRJzRCoNGq6TvLOzEyyGdpvBBcysYxD1XbmkOfWQX2DP+jtgfqUPwHzn0nBCYBUtx6dmtL9p7g0I/Aw+iAJXC2q4MbuKnqyWNfdOGtvu9iXabFWpsXaThIwbqExSRDVEgCva82n8jwXiPhfHEykLjpjvjnKafmYb+Mv7sYAbKAaJ0l5llo/ZTalD+EZtTREH+pfrXvGvRmVpFwpA5B72rdvctRHGLWc2/okRQrXQbsGEAFjP6kagyfSs+enC3Ua2d2fwymFS4GVyGyUpgXxi4W7DEhJOBU1MjdICOY=