name: CI

# Controls when the action will run.
on:
  push:
    branches:
      - master

jobs:
  
  # Check the plugin with kodi-addon-checker
  kodi-addon-checker:
    name: Kodi-addon-checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Run kodi-addon-checker
        run: |
          pip install kodi-addon-checker
          kodi-addon-checker --branch krypton --allow-folder-id-mismatch ./resource.images.catchuptvandmore
  
  # Update repository.catchuptvandmore
  update-repo:
    name: Update repository.catchuptvandmore
    needs: kodi-addon-checker
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Update all repositories
        run: |
          pip install gitpython
          git clone https://github.com/Catch-up-TV-and-More/repository.catchuptvandmore repo
          cd repo
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github@noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.REPO_TOKEN }}@github.com/Catch-up-TV-and-More/repository.catchuptvandmore.git
          ./update_all_repos.sh

  # Prepare and create addon submission pull request to official Kodi repo
  kodi-addon-submitter:
    runs-on: ubuntu-latest
    name: Kodi addon submitter
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Generate distribution zip and submit to official kodi repository
      id: kodi-addon-submitter
      # https://github.com/xbmc/kodi-addon-submitter
      uses: xbmc/action-kodi-addon-submitter@v1.3
      with:
        kodi-repository: repo-resources
        kodi-version: krypton
        addon-id: resource.images.catchuptvandmore
        kodi-matrix: false
        sub-directory: true
      env:
        GH_USERNAME: ${{ github.actor }}
        # https://docs.github.com/en/enterprise-server@3.4/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token
        GH_TOKEN: ${{ secrets.REPO_TOKEN }}
        EMAIL: ${{ secrets.EMAIL }}